version: '2'
services:
  nginx:
    image: hybridispeksi/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp/letsencrypt/www:/tmp/letsencrypt/www
    networks:
      - docker-network
    links:
      - web
  web:
    image: hybridispeksi/web:8eaa074
    container_name: web
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - docker-network
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      # - ./config/my-postgres.conf:/etc/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql.conf'
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
