version: '2'
services:
  nginx:
    image: hybridispeksi/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - docker-network
    links:
      - web
  web:
    image: hybridispeksi/web:latest
    container_name: web
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
