version: '2'
services:
  nginx:
    image: hybridispeksi/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp/letsencrypt/www:/tmp/letsencrypt/www
    networks:
      - docker-network
    links:
      - web
  web:
    image: hybridispeksi/web:latest
    container_name: web
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - docker-network
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      # - ./.pgdata:/var/lib/postgresql/data
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - ./config/my-postgres.conf:/etc/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql.conf'
    networks:
      - docker-network
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   depends_on:
  #     - db
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
  #     PGADMIN_DEFAULT_PASSWORD: pgadmin
  #   volumes:
  #     - ./.pgadmindata/pgadmin:/root/.pgadmin
  #   ports:
  #     - "5050:80"
  #   restart: always
  #   restart: unless-stopped
  #   logging:
  #     driver: none
  #   networks:
  #     - docker-network


networks:
  docker-network:
    driver: bridge
